[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

## Localization break part control
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = "elseif part.control.X or part.control.B then"
position = "before"
payload = '''
elseif part.control.br then
  local height = 0.05
  local gaps = 0.2
  local mid = 0.15
  local sides = (tonumber(part.control.br) - gaps*2 - mid) / 2
  -- spacing
  args.nodes[#args.nodes+1] = {{n=G.UIT.R, config={align = "cm", minh = height}, nodes={}}}
  if sides < gaps then
    args.nodes[#args.nodes+1] = {{n=G.UIT.C, config={align = "cm", colour = G.C.UI.TRANSPARENT_DARK, minw = tonumber(part.control.br), minh = height}}}
  else
    local temp_nodes = {{n=G.UIT.C, config={align = "cm", colour = G.C.UI.TRANSPARENT_DARK, minw = sides, minh = height}, nodes={}},
                        {n=G.UIT.C, config={align = "cm", minw = gaps}, nodes={}},
                        {n=G.UIT.C, config={align = "cm", colour = G.C.UI.TEXT_INACTIVE, minw = mid, minh = height}, nodes={}},
                        {n=G.UIT.C, config={align = "cm", minw = gaps}, nodes={}},
                        {n=G.UIT.C, config={align = "cm", colour = G.C.UI.TRANSPARENT_DARK, minw = sides, minh = height}, nodes={}}}
    args.nodes[#args.nodes+1] = {{n=G.UIT.R, config={align = "cm", minw = tonumber(part.control.br)}, nodes=temp_nodes}}
  end
'''
match_indent = true